-- ====================================================================
-- SCRIPT KHỞI TẠO CƠ SỞ DỮ LIỆU ORACLE CHO HỆ THỐNG PAYMENT HUB
-- ====================================================================

-- 1. Tạo bảng PMH_COMPONENTS (Bảng cấu phần xử lý - Bảng cha)
CREATE TABLE PMH_COMPONENTS (
    COMPONENT_CODE   VARCHAR2(50 CHAR)   NOT NULL PRIMARY KEY,
    COMPONENT_NAME   VARCHAR2(255 CHAR)  NOT NULL,
    MESSAGE_TYPE     VARCHAR2(100 CHAR),  -- Chuẩn tin điện: ISO20022, MT, MX...
    CONNECTION_METHOD VARCHAR2(100 CHAR), -- Phương thức kết nối: API, MQ, SFTP...
    CHECK_TOKEN      VARCHAR2(1 CHAR) DEFAULT 'N', -- Y: Có kiểm tra token, N: Không
    DESCRIPTION      VARCHAR2(4000 CHAR),
    STATUS           NUMBER(1) DEFAULT 1 NOT NULL, -- 1: Mới, 3: Chờ duyệt, 4: Đã duyệt, 5: Từ chối, 7: Hủy duyệt
    IS_ACTIVE        NUMBER(1) DEFAULT 1 NOT NULL, -- 0: Không hoạt động, 1: Hoạt động
    IS_DISPLAY       NUMBER(1) DEFAULT 1 NOT NULL, -- 1: Chưa duyệt (cho phép xóa), 2: Đã duyệt
    NEW_DATA         VARCHAR2(4000 CHAR),
    EFFECTIVE_DATE   DATE NOT NULL,
    END_EFFECTIVE_DATE DATE,
    CREATED_BY       VARCHAR2(50 CHAR),
    CREATED_DATE     DATE DEFAULT SYSDATE,
    UPDATED_BY       VARCHAR2(50 CHAR),
    UPDATED_DATE     DATE DEFAULT SYSDATE
);

-- 2. Tạo bảng chính PMH_GROUP_CATEGORY (Tham số danh mục theo nhóm)
CREATE TABLE PMH_GROUP_CATEGORY (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PARAM_NAME VARCHAR2(255 CHAR) NOT NULL,
    PARAM_VALUE VARCHAR2(255 CHAR) NOT NULL,
    PARAM_TYPE VARCHAR2(255 CHAR) NOT NULL,
    DESCRIPTION VARCHAR2(4000 CHAR),
    COMPONENT_CODE VARCHAR2(255 CHAR) NOT NULL,
    STATUS NUMBER(1) DEFAULT 1 NOT NULL, -- 1: Mới, 3: Chờ duyệt, 4: Đã duyệt, 5: Từ chối, 7: Hủy duyệt
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL, -- 0: Không hoạt động, 1: Hoạt động
    IS_DISPLAY NUMBER(1) DEFAULT 1 NOT NULL, -- 1: Chưa duyệt, 2: Đã duyệt
    NEW_DATA VARCHAR2(4000 CHAR), -- Lưu dữ liệu mới thay đổi dưới dạng JSON trước khi duyệt
    EFFECTIVE_DATE DATE NOT NULL,
    END_EFFECTIVE_DATE DATE,
    CREATED_BY VARCHAR2(50 CHAR),
    CREATED_DATE DATE DEFAULT SYSDATE,
    UPDATED_BY VARCHAR2(50 CHAR),
    UPDATED_DATE DATE DEFAULT SYSDATE
);

-- Ràng buộc độc nhất (Unique Constraint) cho bộ 3
ALTER TABLE PMH_GROUP_CATEGORY ADD CONSTRAINT UQ_GROUP_CATEGORY UNIQUE (PARAM_NAME, PARAM_VALUE, PARAM_TYPE);

-- Ràng buộc khóa ngoại (Foreign Key) tham chiếu cấu phần xử lý
ALTER TABLE PMH_GROUP_CATEGORY ADD CONSTRAINT FK_CATEGORY_COMPONENT 
FOREIGN KEY (COMPONENT_CODE) REFERENCES PMH_COMPONENTS(COMPONENT_CODE);


-- 3. Stored Procedure duyệt bản ghi (Dạng 3)
CREATE OR REPLACE PROCEDURE PROC_APPROVE_GROUP_CATEGORY (
    p_id IN NUMBER,
    p_user IN VARCHAR2,
    p_status OUT NUMBER,
    p_message OUT VARCHAR2
) AS
BEGIN
    UPDATE PMH_GROUP_CATEGORY
    SET STATUS = 4, -- Đã duyệt
        IS_DISPLAY = 2, -- Đã duyệt không cho phép xóa
        UPDATED_BY = p_user,
        UPDATED_DATE = SYSDATE
    WHERE ID = p_id;
    
    IF SQL%ROWCOUNT > 0 THEN
        p_status := 1;
        p_message := 'Duyệt thành công';
    ELSE
        p_status := 0;
        p_message := 'Không tìm thấy bản ghi';
    END IF;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        p_status := -1;
        p_message := SQLERRM;
END;
/

-- 4. Stored Procedure từ chối duyệt (Dạng 3)
CREATE OR REPLACE PROCEDURE PROC_REJECT_GROUP_CATEGORY (
    p_id IN NUMBER,
    p_user IN VARCHAR2,
    p_status OUT NUMBER,
    p_message OUT VARCHAR2
) AS
BEGIN
    UPDATE PMH_GROUP_CATEGORY
    SET STATUS = 5, -- Từ chối duyệt
        UPDATED_BY = p_user,
        UPDATED_DATE = SYSDATE
    WHERE ID = p_id;
    
    IF SQL%ROWCOUNT > 0 THEN
        p_status := 1;
        p_message := 'Từ chối duyệt thành công';
    ELSE
        p_status := 0;
        p_message := 'Không tìm thấy bản ghi';
    END IF;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        p_status := -1;
        p_message := SQLERRM;
END;
/


-- 5. Stored Procedure duyệt Cấu phần xử lý
CREATE OR REPLACE PROCEDURE PROC_APPROVE_COMPONENT (
    p_code IN VARCHAR2,
    p_user IN VARCHAR2,
    p_status OUT NUMBER,
    p_message OUT VARCHAR2
) AS
BEGIN
    UPDATE PMH_COMPONENTS
    SET STATUS = 4,
        IS_DISPLAY = 2,
        UPDATED_BY = p_user,
        UPDATED_DATE = SYSDATE
    WHERE COMPONENT_CODE = p_code;

    IF SQL%ROWCOUNT > 0 THEN
        p_status := 1;
        p_message := 'Duyệt thành công';
    ELSE
        p_status := 0;
        p_message := 'Không tìm thấy bản ghi';
    END IF;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        p_status := -1;
        p_message := SQLERRM;
END;
/

-- 6. Stored Procedure từ chối duyệt Cấu phần xử lý
CREATE OR REPLACE PROCEDURE PROC_REJECT_COMPONENT (
    p_code IN VARCHAR2,
    p_user IN VARCHAR2,
    p_status OUT NUMBER,
    p_message OUT VARCHAR2
) AS
BEGIN
    UPDATE PMH_COMPONENTS
    SET STATUS = 5,
        UPDATED_BY = p_user,
        UPDATED_DATE = SYSDATE
    WHERE COMPONENT_CODE = p_code;

    IF SQL%ROWCOUNT > 0 THEN
        p_status := 1;
        p_message := 'Từ chối duyệt thành công';
    ELSE
        p_status := 0;
        p_message := 'Không tìm thấy bản ghi';
    END IF;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        p_status := -1;
        p_message := SQLERRM;
END;
/


-- 7. Insert dữ liệu mẫu kiểm thử
INSERT INTO PMH_COMPONENTS (COMPONENT_CODE, COMPONENT_NAME, MESSAGE_TYPE, CONNECTION_METHOD, CHECK_TOKEN, DESCRIPTION, STATUS, IS_ACTIVE, IS_DISPLAY, EFFECTIVE_DATE, CREATED_BY, UPDATED_BY)
VALUES ('RLT', 'Real-time Payment Component', 'ISO20022', 'API', 'Y', 'Cấu phần xử lý thanh toán thời gian thực', 4, 1, 2, TO_DATE('2026-01-01', 'YYYY-MM-DD'), 'ADMIN', 'ADMIN');

INSERT INTO PMH_COMPONENTS (COMPONENT_CODE, COMPONENT_NAME, MESSAGE_TYPE, CONNECTION_METHOD, CHECK_TOKEN, DESCRIPTION, STATUS, IS_ACTIVE, IS_DISPLAY, EFFECTIVE_DATE, CREATED_BY, UPDATED_BY)
VALUES ('FIM', 'Financial Information Module', 'MT', 'MQ', 'N', 'Module thông tin tài chính', 4, 1, 2, TO_DATE('2026-01-01', 'YYYY-MM-DD'), 'ADMIN', 'ADMIN');

INSERT INTO PMH_COMPONENTS (COMPONENT_CODE, COMPONENT_NAME, MESSAGE_TYPE, CONNECTION_METHOD, CHECK_TOKEN, DESCRIPTION, STATUS, IS_ACTIVE, IS_DISPLAY, EFFECTIVE_DATE, CREATED_BY, UPDATED_BY)
VALUES ('TRA', 'Transaction Router Agent', 'MX', 'SFTP', 'N', 'Cấu phần định tuyến giao dịch', 4, 1, 2, TO_DATE('2026-01-01', 'YYYY-MM-DD'), 'ADMIN', 'ADMIN');

INSERT INTO PMH_GROUP_CATEGORY (PARAM_NAME, PARAM_VALUE, PARAM_TYPE, DESCRIPTION, COMPONENT_CODE, STATUS, IS_ACTIVE, IS_DISPLAY, EFFECTIVE_DATE, CREATED_BY, UPDATED_BY)
VALUES ('SOA', '01', 'STATUS_TYPE', 'Tham số trạng thái dịch vụ SOA', 'RLT', 4, 1, 2, TO_DATE('2026-01-01', 'YYYY-MM-DD'), 'ADMIN', 'ADMIN');

INSERT INTO PMH_GROUP_CATEGORY (PARAM_NAME, PARAM_VALUE, PARAM_TYPE, DESCRIPTION, COMPONENT_CODE, STATUS, IS_ACTIVE, IS_DISPLAY, EFFECTIVE_DATE, CREATED_BY, UPDATED_BY)
VALUES ('ERROR_CODE', 'ERR001', 'ERROR_CODE', 'Lỗi không xác định hệ thống', 'FIM', 1, 1, 1, TO_DATE('2026-03-01', 'YYYY-MM-DD'), 'USER01', 'USER01');

COMMIT;

-- ====================================================================
-- 8. Bảng PMH_AUDIT_LOG (Nhật ký lịch sử thao tác)
-- ====================================================================
CREATE TABLE PMH_AUDIT_LOG (
    ID            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MODULE        VARCHAR2(50 CHAR)   NOT NULL,   -- 'GROUP_CATEGORY' | 'COMPONENT'
    RECORD_ID     VARCHAR2(100 CHAR)  NOT NULL,   -- ID hoặc COMPONENT_CODE của bản ghi
    ACTION        VARCHAR2(100 CHAR)  NOT NULL,   -- 'Tạo mới' | 'Cập nhật' | 'Xóa' | 'Gửi duyệt' | 'Phê duyệt' | 'Từ chối' | 'Hủy duyệt'
    PERFORMED_BY  VARCHAR2(100 CHAR)  NOT NULL,   -- Username người thực hiện
    ACTION_DATE   DATE DEFAULT SYSDATE NOT NULL,  -- Thời điểm thực hiện
    OLD_DATA      CLOB,                            -- JSON dữ liệu trước khi thay đổi
    NEW_DATA_LOG  CLOB,                            -- JSON dữ liệu sau khi thay đổi
    DESCRIPTION   VARCHAR2(4000 CHAR),             -- Mô tả chi tiết hành động
    STATUS_BEFORE NUMBER(1),                       -- Trạng thái trước (1,3,4,5,7)
    STATUS_AFTER  NUMBER(1),                       -- Trạng thái sau
    IP_ADDRESS    VARCHAR2(100 CHAR)               -- Địa chỉ IP của client gửi yêu cầu
);

-- Index cho query hiệu quả theo module + record
CREATE INDEX IDX_AUDIT_MODULE_RECORD ON PMH_AUDIT_LOG (MODULE, RECORD_ID);
-- Index cho sort theo thời gian
CREATE INDEX IDX_AUDIT_ACTION_DATE   ON PMH_AUDIT_LOG (ACTION_DATE DESC);

CREATE TABLE PMH_APP_USERS (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USERNAME VARCHAR2(50 CHAR) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR2(255 CHAR) NOT NULL,
    FULL_NAME VARCHAR2(100 CHAR),
    ROLE VARCHAR2(50 CHAR) NOT NULL,
    FAILED_LOGIN_ATTEMPTS NUMBER(10) DEFAULT 0 NOT NULL,
    LOCKOUT_UNTIL TIMESTAMP
);
